name: Java CI with Maven

on:
  push:
    branches:
      - main  # Executa o CI quando houver push na branch main
  pull_request:
    branches:
      - main  # Executa o CI quando houver PR para a branch main

jobs:
  build:

    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu para rodar o job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Faz checkout do código para o workflow

    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Configura o JDK 17 para o ambiente
      with:
        java-version: '17'  # Versão do JDK
        distribution: 'temurin'  # Usando o distribuidor Temurin do OpenJDK

    - name: Cache Maven dependencies
      uses: actions/cache@v3  # Cache para as dependências do Maven
      with:
        path: ~/.m2/repository  # Caminho para o repositório local do Maven
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache baseado no hash do pom.xml
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and Test with Maven
      run: mvn clean verify -DskipTests=false  # Faz a limpeza, build e executa os testes

